{
 "title": "Speedtest",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "dl_maxspeed", "label": "download max speed", "query": "250" },
   { "name": "ul_maxspeed", "label": "upload max speed", "query": "25" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "stat",
   "description": "Speedtest errors since last restart",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_test_errors) without (pod, instance)"
    }
   ]
  },
  {
   "title": "Speedtest Results",
   "type": "timeseries",
   "description": "Upload and download speeds",
   "gridPos": { "h": 12, "w": 22, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg (speedtest_upload_mbps) without (instance, pod)",
     "legendFormat": "Upload Speed"
    },
    {
     "expr": "avg (speedtest_download_mbps) without (instance, pod)",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Timeouts since last restart",
   "type": "stat",
   "description": "Number of times the speedtest has exceeded the timeout specified in options (2 min by default).",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(speedtest_test_timeouts) without (pod, instance)",
     "legendFormat": "Speedtest timesouts"
    }
   ]
  },
  {
   "title": "Speedtest ping latency",
   "type": "timeseries",
   "description": "Latency to test server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg (speedtest_ping_latency_ms) without (server_id, test_id,pod,instance)",
     "legendFormat": "Ping Latency"
    }
   ]
  },
  {
   "title": "Speedtest Test Duration",
   "type": "timeseries",
   "description": "Time the test took to complete",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg (speedtest_duration_ms) without (server_id,test_id,pod,instance)",
     "legendFormat": "Test Duration"
    }
   ]
  }
 ]
}