apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: speedtest-exporter
    spec:
      containers:
      - command:
        - /speedtest-exporter
        - exporter
        image: quay.io/lisa/speedtest-exporter:latest
        imagePullPolicy: IfNotPresent
        name: speedtest-exporter
      restartPolicy: Always
      terminationGracePeriodSeconds: 30