apiVersion: v1
kind: Service
metadata:
  labels:
    app: speedtest-exporter
  name: speedtest-exporter
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: speedtest-exporter
  sessionAffinity: None
  type: ClusterIP